// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "autoIdentifyNewItems": boolean;
      "newItemDelay": number;
      "skipAlreadyIdentified": boolean;
      "dblpEnabled": boolean;
      "dblpEndpoint": string;
      "casEnabled": boolean;
      "casCacheTtlDays": number;
      "casRequestInterval": number;
      "deleteLegacyNoteAfterMigration": boolean;
      "showSummaryColumn": boolean;
      "showCcfColumn": boolean;
      "showCasColumn": boolean;
      "showCitationColumn": boolean;
      "summaryColumnLabel": string;
      "ccfColumnLabel": string;
      "casColumnLabel": string;
      "citationColumnLabel": string;
      "summaryTemplate": string;
      "placeholderNoCcf": string;
      "placeholderPreprint": string;
      "placeholderNotApplicable": string;
      "placeholderNoCas": string;
      "ccfPrefix": boolean;
      "separator": string;
      "showItemPaneRow": boolean;
      "aliasMapping": string;
    };
  }
}
